### ISSUE TITLE
License: Why 2-clause and not 3?

### ISSUE THREAD

**Issue by pllim** [astrofrog/batchpr#4]
Why BSD 2-clause instead of 3-clause? Just curious.

**Comment by astrofrog** [comment]
Because it started off as an individual project and not under an organizational umbrella so I thought one of the clauses didn't apply. Happy to change it though.

**Comment by pllim** [comment]
I am no repo lawyer. This is under your account still, so probably okay? 🤷‍♀️ 

Should we keep this open if you want to revisit in the future? If not, feel free to close.

**Comment by astrofrog** [comment]
Let's close this and just revisit if we move the repo
